# Generated by Django 4.0 on 2022-05-05 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Moscow', max_length=255, verbose_name='Название города')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(verbose_name='Температура')),
                ('humidity', models.IntegerField(verbose_name='Влажность')),
                ('pressure', models.IntegerField(verbose_name='Давление')),
                ('rain_chance', models.IntegerField(verbose_name='Вероятность дождя')),
                ('part_of_the_day', models.CharField(max_length=15, verbose_name='Часть дня')),
                ('visibility', models.CharField(max_length=25, verbose_name='Видимость')),
                ('speed_wind', models.CharField(max_length=25, verbose_name='Скорость ветра')),
                ('cloudiness', models.CharField(max_length=25, verbose_name='Облачность')),
                ('temp_feels_like', models.CharField(max_length=25, verbose_name='Ощущается как')),
                ('bookmark', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.location', verbose_name='Локация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='ChosenWeatherCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.weathercard', verbose_name='Погодная карточка')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь')),
            ],
        ),
    ]
