# Generated by Django 4.0 on 2022-03-03 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Название города')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(verbose_name='Температура')),
                ('humidity', models.IntegerField(verbose_name='Влажность')),
                ('pressure', models.IntegerField(verbose_name='Давление')),
                ('rain_chance', models.IntegerField(verbose_name='Вероятность дождя')),
                ('part_of_the_day', models.CharField(max_length=15, verbose_name='Часть дня')),
                ('visibility', models.CharField(max_length=25, verbose_name='Видимость')),
                ('speed_wind', models.CharField(max_length=25, verbose_name='Скорость ветра')),
                ('cloudiness', models.CharField(max_length=25, verbose_name='Облачность')),
                ('temp_feels_like', models.CharField(max_length=25, verbose_name='Ощущается как')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.location', verbose_name='Локация')),
            ],
        ),
    ]
