# Generated by Django 4.0 on 2022-05-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathercard',
            name='user',
        ),
    ]
