# Generated by Django 4.0 on 2022-02-25 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DayWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_day', models.CharField(max_length=35, verbose_name='День')),
                ('humidity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_humidity', to='app.weathercard')),
                ('part_of_the_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_part_of_the_day', to='app.weathercard')),
                ('pressure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_pressure', to='app.weathercard')),
                ('rain_chance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_rin_chance', to='app.weathercard')),
                ('temperature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_temperature', to='app.weathercard')),
            ],
        ),
    ]
