# Generated by Django 4.0 on 2022-02-25 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_search_dayweather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathercard',
            name='humidity',
            field=models.IntegerField(verbose_name='Влажность'),
        ),
        migrations.AlterField(
            model_name='weathercard',
            name='part_of_the_day',
            field=models.CharField(max_length=15, verbose_name='Часть дня'),
        ),
        migrations.AlterField(
            model_name='weathercard',
            name='pressure',
            field=models.IntegerField(verbose_name='Давление'),
        ),
        migrations.AlterField(
            model_name='weathercard',
            name='rain_chance',
            field=models.IntegerField(verbose_name='Вероятность дождя'),
        ),
        migrations.AlterField(
            model_name='weathercard',
            name='temperature',
            field=models.IntegerField(verbose_name='Температура'),
        ),
        migrations.CreateModel(
            name='WeatherTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_humidity2', to='app.weathercard')),
                ('part_of_the_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_part_of_the_day2', to='app.weathercard')),
                ('pressure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_pressure2', to='app.weathercard')),
                ('rain_chance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_rin_chance2', to='app.weathercard')),
                ('temperature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_temperature2', to='app.weathercard')),
            ],
        ),
        migrations.CreateModel(
            name='CityWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=65, verbose_name='Название города')),
                ('humidity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_humidity1', to='app.weathercard')),
                ('part_of_the_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_part_of_the_day1', to='app.weathercard')),
                ('pressure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_pressure1', to='app.weathercard')),
                ('rain_chance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_rin_chance1', to='app.weathercard')),
                ('temperature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_temperature1', to='app.weathercard')),
            ],
        ),
    ]
