# Generated by Django 4.0 on 2022-03-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_location_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='Moscow', max_length=255, verbose_name='Название города'),
        ),
    ]
